package storage

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"regexp"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

var ec2ProducerUserID = regexp.MustCompile(`^AROA[A-Z0-9]{17}:i-([a-f0-9]{8}|[a-f0-9]{17})$`)
var producerRoleID = regexp.MustCompile(`^AROA[A-Z0-9]{17}$`)
var producerRoleARN = regexp.MustCompile(`^arn:aws:iam::[0-9]{12}:role/[a-zA-Z0-9_+=,.@/-]+$`)

// PolicySHA256 is an operator-approved trust anchor, generated by the optional
// infrastructure module. A matching STS session name alone is NOT EC2 proof:
// the approved policy must enforce SourceInstanceARN and own-userid writes.
type ProtectedCustodyConfig struct {
	Destination                                   CustodyDestination
	ProducerRoleARN, ProducerRoleID, PolicySHA256 string
	RetentionDays                                 int
}
type EC2Producer struct{ AccountID, RoleARN, UserID, InstanceID string }
type ProtectedAWSCustody struct {
	store    *awsCustody
	producer EC2Producer
	config   ProtectedCustodyConfig
}

func (p *ProtectedAWSCustody) Destination() CustodyDestination { return p.store.destination }
func (p *ProtectedAWSCustody) Producer() EC2Producer           { return p.producer }
func (p *ProtectedAWSCustody) CreateExact(ctx context.Context, c CustodyClaim, data []byte) (CustodyReceipt, error) {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	if err := verifyProtectedBucket(ctx, p.store.client, p.config); err != nil {
		return CustodyReceipt{}, err
	}
	return p.store.CreateExact(ctx, c, data)
}
func (p *ProtectedAWSCustody) VerifyExact(ctx context.Context, c CustodyClaim) (CustodyReceipt, error) {
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	if err := verifyProtectedBucket(ctx, p.store.client, p.config); err != nil {
		return CustodyReceipt{}, err
	}
	return p.store.VerifyExact(ctx, c)
}

// VerifyVersion replays an exact version with producer credentials. Independent
// consumers use NewProtectedCustodyReader with their separate reader role.
func (p *ProtectedAWSCustody) VerifyVersion(ctx context.Context, c CustodyClaim, version string) (CustodyReceipt, error) {
	if version == "" || version == "null" {
		return CustodyReceipt{}, errors.New("exact custody version required")
	}
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	if err := verifyProtectedBucket(ctx, p.store.client, p.config); err != nil {
		return CustodyReceipt{}, err
	}
	return p.store.verifyExactVersion(ctx, c, version)
}

func (c ProtectedCustodyConfig) Validate() error {
	d := c.Destination
	if d.ClaimedHostID != "" || d.ProducerUserID != "" {
		return errors.New("protected producer identity cannot be supplied as a claim")
	}
	d.ClaimedHostID = "validation"
	if err := d.Validate(); err != nil {
		return err
	}
	if !producerRoleARN.MatchString(c.ProducerRoleARN) || !strings.HasPrefix(c.ProducerRoleARN, "arn:aws:iam::"+d.AccountID+":role/") || !producerRoleID.MatchString(c.ProducerRoleID) || !custodyHash.MatchString(c.PolicySHA256) || c.RetentionDays < 1 || c.RetentionDays > 36500 {
		return errors.New("explicit producer role, policy hash and retention required")
	}
	return nil
}
func deriveEC2Producer(c ProtectedCustodyConfig, identity *sts.GetCallerIdentityOutput) (EC2Producer, error) {
	if err := c.Validate(); err != nil {
		return EC2Producer{}, err
	}
	if identity == nil {
		return EC2Producer{}, errors.New("missing STS identity")
	}
	user := aws.ToString(identity.UserId)
	parts := strings.Split(user, ":")
	if aws.ToString(identity.Account) != c.Destination.AccountID || !ec2ProducerUserID.MatchString(user) || parts[0] != c.ProducerRoleID {
		return EC2Producer{}, errors.New("producer account or EC2-form role identity mismatch")
	}
	roleName := c.ProducerRoleARN[strings.LastIndex(c.ProducerRoleARN, "/")+1:]
	if aws.ToString(identity.Arn) != "arn:aws:sts::"+c.Destination.AccountID+":assumed-role/"+roleName+"/"+parts[1] {
		return EC2Producer{}, errors.New("producer role session ARN mismatch")
	}
	return EC2Producer{AccountID: c.Destination.AccountID, RoleARN: c.ProducerRoleARN, UserID: user, InstanceID: parts[1]}, nil
}
func NewProtectedAWSCustody(ctx context.Context, c ProtectedCustodyConfig) (*ProtectedAWSCustody, error) {
	if err := c.Validate(); err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(c.Destination.Region))
	if err != nil {
		return nil, err
	}
	return newProtectedAWSCustodyConfigured(ctx, c, cfg)
}
func newProtectedAWSCustodyConfigured(ctx context.Context, c ProtectedCustodyConfig, cfg aws.Config) (*ProtectedAWSCustody, error) {
	if err := c.Validate(); err != nil {
		return nil, err
	}
	temporary := c.Destination
	temporary.ClaimedHostID = "unbound"
	base, err := newAWSCustodyConfigured(ctx, temporary, cfg)
	if err != nil {
		return nil, err
	}
	store := base.(*awsCustody)
	producer, err := deriveEC2Producer(c, store.identity)
	if err != nil {
		return nil, err
	}
	if err = verifyProtectedBucket(ctx, store.client, c); err != nil {
		return nil, err
	}
	store.destination = c.Destination
	store.destination.ProducerUserID = producer.UserID
	store.retentionDays = c.RetentionDays
	return &ProtectedAWSCustody{store: store, producer: producer, config: c}, nil
}
func canonicalPolicyHash(raw string) (string, error) {
	var policy map[string]any
	if err := json.Unmarshal([]byte(raw), &policy); err != nil {
		return "", err
	}
	if policy == nil {
		return "", errors.New("missing policy object")
	}
	data, err := json.Marshal(policy)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}
func verifyProtectedBucket(ctx context.Context, client *s3.Client, c ProtectedCustodyConfig) error {
	owner, bucket := aws.String(c.Destination.AccountID), aws.String(c.Destination.Bucket)
	policy, err := client.GetBucketPolicy(ctx, &s3.GetBucketPolicyInput{Bucket: bucket, ExpectedBucketOwner: owner})
	if err != nil {
		return err
	}
	hash, err := canonicalPolicyHash(aws.ToString(policy.Policy))
	if err != nil {
		return err
	}
	if hash != c.PolicySHA256 {
		return errors.New("protected bucket policy evidence mismatch")
	}
	versions, err := client.GetBucketVersioning(ctx, &s3.GetBucketVersioningInput{Bucket: bucket, ExpectedBucketOwner: owner})
	if err != nil {
		return err
	}
	if versions.Status != types.BucketVersioningStatusEnabled {
		return errors.New("protected bucket versioning required")
	}
	lock, err := client.GetObjectLockConfiguration(ctx, &s3.GetObjectLockConfigurationInput{Bucket: bucket, ExpectedBucketOwner: owner})
	if err != nil {
		return err
	}
	if lock.ObjectLockConfiguration == nil || lock.ObjectLockConfiguration.ObjectLockEnabled != types.ObjectLockEnabledEnabled || lock.ObjectLockConfiguration.Rule == nil || lock.ObjectLockConfiguration.Rule.DefaultRetention == nil {
		return errors.New("protected retention configuration missing")
	}
	retention := lock.ObjectLockConfiguration.Rule.DefaultRetention
	if retention.Mode != types.ObjectLockRetentionModeGovernance || retention.Years != nil || aws.ToInt32(retention.Days) != int32(c.RetentionDays) {
		return errors.New("protected retention policy mismatch")
	}
	return nil
}
